Update s390x data layout
https://github.com/llvm/llvm-project/pull/176041 changed the default data layout for s390x, causing tests to fail against ToT LLVM, e.g.

 error: data-layout for target `s390x-unknown-linux-gnu`, `E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-v128:64-a:8:16-n32:64`, differs from LLVM target's `s390x-unknown-linux-gnu` default layout, `E-S64-m:e-i1:8:16-i8:8:16-i64:64-f128:64-v128:64-a:8:16-n32:64`